server:
  port: 9527

eureka:
  instance:
    hostname:  cloud-gateway-service

  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true


spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      routes:
        - id: payment_routh   #路由的ID 没有固定的规则但是要求是唯一的 建议配合服务名
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**  # 断言 路径匹配进行路由

        -  id: payment_touth2
           uri: lb://cloud-payment-service  #匹配后提供的服务的路由地址
#           uri: http://localhost:8001
           predicates:
             - Path= /payment/lb/**  #断言路径匹配的进行路由
#             - After=2020-03-24T22:16:20.782+08:00[Asia/Shanghai]
#             - Cookie=username,mage
#             - Header=X-Request-Id,\d+ #请求头要求X-Request-I格式 为整数的正则表达式
      discovery:
        locator:
          enabled: true