server:
  port: 8001

spring:
  application:
    name: cloud-provider-hyxtrix-payment

eureka:
  client:
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com/eureka/
      defaultZone: http://eureka7001.com:7001/eureka
    fetch-registry: true
    register-with-eureka: true